//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblThree.Applications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TumblThree.Applications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is up to date..
        /// </summary>
        public static string ApplicationUpToDate {
            get {
                return ResourceManager.GetString("ApplicationUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio caption: {0}.
        /// </summary>
        public static string AudioCaption {
            get {
                return ResourceManager.GetString("AudioCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failure: {0}.
        /// </summary>
        public static string AuthenticationFailure {
            get {
                return ResourceManager.GetString("AuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blog already exist:  {0}.
        /// </summary>
        public static string BlogAlreadyExist {
            get {
                return ResourceManager.GetString("BlogAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blog is offline: {0}.
        /// </summary>
        public static string BlogIsOffline {
            get {
                return ResourceManager.GetString("BlogIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BlogTypesAll {
            get {
                return ResourceManager.GetString("BlogTypesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never finished.
        /// </summary>
        public static string BlogTypesNeverFinished {
            get {
                return ResourceManager.GetString("BlogTypesNeverFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BlogTypesNone {
            get {
                return ResourceManager.GetString("BlogTypesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once finished.
        /// </summary>
        public static string BlogTypesOnceFinished {
            get {
                return ResourceManager.GetString("BlogTypesOnceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body: {0].
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation: {0}.
        /// </summary>
        public static string Conversation {
            get {
                return ResourceManager.GetString("Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the blog:  {0}.
        /// </summary>
        public static string CouldNotAddBlog {
            get {
                return ResourceManager.GetString("CouldNotAddBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load file in library: {0}.
        /// </summary>
        public static string CouldNotLoadLibrary {
            get {
                return ResourceManager.GetString("CouldNotLoadLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queuelist could not be loaded. Maybe some referenced blogs do not exist anymore..
        /// </summary>
        public static string CouldNotLoadQueuelist {
            get {
                return ResourceManager.GetString("CouldNotLoadQueuelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file could not be opened..
        /// </summary>
        public static string CouldNotOpenFiles {
            get {
                return ResourceManager.GetString("CouldNotOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the blog: {0}.
        /// </summary>
        public static string CouldNotRemoveBlog {
            get {
                return ResourceManager.GetString("CouldNotRemoveBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the blog: {0}.
        /// </summary>
        public static string CouldNotRemoveBlogIndex {
            get {
                return ResourceManager.GetString("CouldNotRemoveBlogIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore user interface settings..
        /// </summary>
        public static string CouldNotRestoreUISettings {
            get {
                return ResourceManager.GetString("CouldNotRestoreUISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the blog: {0}.
        /// </summary>
        public static string CouldNotSaveBlog {
            get {
                return ResourceManager.GetString("CouldNotSaveBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queuelist could not be saved..
        /// </summary>
        public static string CouldNotSaveQueueList {
            get {
                return ResourceManager.GetString("CouldNotSaveQueueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the OAuth manager.
        /// </summary>
        public static string CouldNotStartOAuthManager {
            get {
                return ResourceManager.GetString("CouldNotStartOAuthManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crawler thread encountered an error..
        /// </summary>
        public static string CrawlerError {
            get {
                return ResourceManager.GetString("CrawlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crawling.
        /// </summary>
        public static string Crawling {
            get {
                return ResourceManager.GetString("Crawling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the following blog indices including all downloaded files?
        ///{0}..
        /// </summary>
        public static string DeleteBlogsAndFilesDialog {
            get {
                return ResourceManager.GetString("DeleteBlogsAndFilesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the following blog indices?
        ///{0}..
        /// </summary>
        public static string DeleteBlogsDialog {
            get {
                return ResourceManager.GetString("DeleteBlogsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space on the disk..
        /// </summary>
        public static string DiskFull {
            get {
                return ResourceManager.GetString("DiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt.
        /// </summary>
        public static string ExportFileFilter {
            get {
                return ResourceManager.GetString("ExportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        public static string ExportFileFilterExtension {
            get {
                return ResourceManager.GetString("ExportFileFilterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answers.txt.
        /// </summary>
        public static string FileNameAnswers {
            get {
                return ResourceManager.GetString("FileNameAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audios_url.txt.
        /// </summary>
        public static string FileNameAudios {
            get {
                return ResourceManager.GetString("FileNameAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversations.txt.
        /// </summary>
        public static string FileNameConversations {
            get {
                return ResourceManager.GetString("FileNameConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to links.txt.
        /// </summary>
        public static string FileNameLinks {
            get {
                return ResourceManager.GetString("FileNameLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audios.txt.
        /// </summary>
        public static string FileNameMetaAudio {
            get {
                return ResourceManager.GetString("FileNameMetaAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.txt.
        /// </summary>
        public static string FileNameMetaPhoto {
            get {
                return ResourceManager.GetString("FileNameMetaPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos.txt.
        /// </summary>
        public static string FileNameMetaVideo {
            get {
                return ResourceManager.GetString("FileNameMetaVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images_url.txt.
        /// </summary>
        public static string FileNamePhotos {
            get {
                return ResourceManager.GetString("FileNamePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quotes.txt.
        /// </summary>
        public static string FileNameQuotes {
            get {
                return ResourceManager.GetString("FileNameQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texts.txt.
        /// </summary>
        public static string FileNameTexts {
            get {
                return ResourceManager.GetString("FileNameTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos_url.txt.
        /// </summary>
        public static string FileNameVideos {
            get {
                return ResourceManager.GetString("FileNameVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id3: Album: {0}.
        /// </summary>
        public static string Id3Album {
            get {
                return ResourceManager.GetString("Id3Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id3: Artist: {0}.
        /// </summary>
        public static string Id3Artist {
            get {
                return ResourceManager.GetString("Id3Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id3: Title: {0}.
        /// </summary>
        public static string Id3Title {
            get {
                return ResourceManager.GetString("Id3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id3: Track: {0}.
        /// </summary>
        public static string Id3Track {
            get {
                return ResourceManager.GetString("Id3Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id3: Year: {0}.
        /// </summary>
        public static string Id3Year {
            get {
                return ResourceManager.GetString("Id3Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit exceeded: {0}. You should lower the connections to the tumblr api in the Settings-&gt;Connection pane..
        /// </summary>
        public static string LimitExceeded {
            get {
                return ResourceManager.GetString("LimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link: {0}.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxBytesPerSecond has to be non-negative.
        /// </summary>
        public static string MaxBytePerSecond {
            get {
                return ResourceManager.GetString("MaxBytePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available for download : {0}.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to tumblr.com for downloading {0}. Go to the Settings-&gt;Authenticate..
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protected blog: {0}. You need to enter the password in the Details..
        /// </summary>
        public static string PasswordProtected {
            get {
                return ResourceManager.GetString("PasswordProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden password protected or offline blog detected: {0}. You need to enter the password in the Details..
        /// </summary>
        public static string PasswordProtectedOrOffline {
            get {
                return ResourceManager.GetString("PasswordProtectedOrOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo caption: {0}.
        /// </summary>
        public static string PhotoCaption {
            get {
                return ResourceManager.GetString("PhotoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo set urls: {0}.
        /// </summary>
        public static string PhotoSetUrl {
            get {
                return ResourceManager.GetString("PhotoSetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo url: {0}.
        /// </summary>
        public static string PhotoUrl {
            get {
                return ResourceManager.GetString("PhotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post id: {0}.
        /// </summary>
        public static string PostId {
            get {
                return ResourceManager.GetString("PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A post from {0} was not parsable. Setting &apos;posts per page&apos; to 1 in the Details might increase the downloadable content..
        /// </summary>
        public static string PostNotParsable {
            get {
                return ResourceManager.GetString("PostNotParsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post url: {0}.
        /// </summary>
        public static string PostUrl {
            get {
                return ResourceManager.GetString("PostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}..
        /// </summary>
        public static string ProgressDownloadImage {
            get {
                return ResourceManager.GetString("ProgressDownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated {0} tumblr post urls out of {1} total posts..
        /// </summary>
        public static string ProgressGetUrlLong {
            get {
                return ResourceManager.GetString("ProgressGetUrlLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated {0} tumblr blog sites..
        /// </summary>
        public static string ProgressGetUrlShort {
            get {
                return ResourceManager.GetString("ProgressGetUrlShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already downloaded, skipping ...
        /// </summary>
        public static string ProgressSkipFile {
            get {
                return ResourceManager.GetString("ProgressSkipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating unique downloads, removing duplicates ....
        /// </summary>
        public static string ProgressUniqueDownloads {
            get {
                return ResourceManager.GetString("ProgressUniqueDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queuelist.
        /// </summary>
        public static string Queuelist {
            get {
                return ResourceManager.GetString("Queuelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote: {0}.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reblog key: {0}.
        /// </summary>
        public static string ReblogKey {
            get {
                return ResourceManager.GetString("ReblogKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reblog name: {0}.
        /// </summary>
        public static string ReblogName {
            get {
                return ResourceManager.GetString("ReblogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reblog url: {0}.
        /// </summary>
        public static string ReblogUrl {
            get {
                return ResourceManager.GetString("ReblogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug: {0}.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary: {0}.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: {0}.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        public static string Textfile {
            get {
                return ResourceManager.GetString("Textfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection timout occured during {0} of {1}..
        /// </summary>
        public static string TimeoutReached {
            get {
                return ResourceManager.GetString("TimeoutReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url with slug: {0}.
        /// </summary>
        public static string UrlWithSlug {
            get {
                return ResourceManager.GetString("UrlWithSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video caption: {0}.
        /// </summary>
        public static string VideoCaption {
            get {
                return ResourceManager.GetString("VideoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video player: {0}.
        /// </summary>
        public static string VideoPlayer {
            get {
                return ResourceManager.GetString("VideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source: {0}.
        /// </summary>
        public static string VideoSource {
            get {
                return ResourceManager.GetString("VideoSource", resourceCulture);
            }
        }
    }
}
