//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblThree.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TumblThree.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gif.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json.
        /// </summary>
        public static string json {
            get {
                return ResourceManager.GetString("json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2mb gif.
        /// </summary>
        public static string max2mbgif {
            get {
                return ResourceManager.GetString("max2mbgif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5mb gif.
        /// </summary>
        public static string max5mbgif {
            get {
                return ResourceManager.GetString("max5mbgif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mjpg.
        /// </summary>
        public static string mjpg {
            get {
                return ResourceManager.GetString("mjpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp4.
        /// </summary>
        public static string mp4 {
            get {
                return ResourceManager.GetString("mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poster.
        /// </summary>
        public static string poster {
            get {
                return ResourceManager.GetString("poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webm.
        /// </summary>
        public static string webm {
            get {
                return ResourceManager.GetString("webm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webp.
        /// </summary>
        public static string webp {
            get {
                return ResourceManager.GetString("webp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
    }
}
