//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblThree.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TumblThree.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blog.
        /// </summary>
        public static string AddBlog {
            get {
                return ResourceManager.GetString("AddBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blogs to the queue..
        /// </summary>
        public static string AutoDownloadBlogs {
            get {
                return ResourceManager.GetString("AutoDownloadBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Bandwidth (KB/s).
        /// </summary>
        public static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 0 and 9,000,000,000,000,000..
        /// </summary>
        public static string BandwidthRangeError {
            get {
                return ResourceManager.GetString("BandwidthRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog settings.
        /// </summary>
        public static string BlogSettings {
            get {
                return ResourceManager.GetString("BlogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog stats:.
        /// </summary>
        public static string BlogStatistics {
            get {
                return ResourceManager.GetString("BlogStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Blogtype {
            get {
                return ResourceManager.GetString("Blogtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BlogtypeAll {
            get {
                return ResourceManager.GetString("BlogtypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string BlogtypeInstagram {
            get {
                return ResourceManager.GetString("BlogtypeInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr.
        /// </summary>
        public static string BlogtypeTumblr {
            get {
                return ResourceManager.GetString("BlogtypeTumblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr Liked-by.
        /// </summary>
        public static string BlogtypeTumblrLikedBy {
            get {
                return ResourceManager.GetString("BlogtypeTumblrLikedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr Hidden.
        /// </summary>
        public static string BlogtypeTumblrPrivate {
            get {
                return ResourceManager.GetString("BlogtypeTumblrPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr Search.
        /// </summary>
        public static string BlogtypeTumblrSearch {
            get {
                return ResourceManager.GetString("BlogtypeTumblrSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr Tag Search.
        /// </summary>
        public static string BlogtypeTumblrTagSearch {
            get {
                return ResourceManager.GetString("BlogtypeTumblrTagSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string BlogtypeTwitter {
            get {
                return ResourceManager.GetString("BlogtypeTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL:.
        /// </summary>
        public static string BlogUrl {
            get {
                return ResourceManager.GetString("BlogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check directory for files.
        /// </summary>
        public static string CheckDirectoryForFiles {
            get {
                return ResourceManager.GetString("CheckDirectoryForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check blog online status.
        /// </summary>
        public static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check blog online status on startup.
        /// </summary>
        public static string CheckStatusOnStartup {
            get {
                return ResourceManager.GetString("CheckStatusOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        public static string ClearQueue {
            get {
                return ResourceManager.GetString("ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Clipboard.
        /// </summary>
        public static string ClipboardMonitor {
            get {
                return ResourceManager.GetString("ClipboardMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent blogs.
        /// </summary>
        public static string ConcurrentBlogs {
            get {
                return ResourceManager.GetString("ConcurrentBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent connections.
        /// </summary>
        public static string ConcurrentConnections {
            get {
                return ResourceManager.GetString("ConcurrentConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent video connections.
        /// </summary>
        public static string ConcurrentVideoConnections {
            get {
                return ResourceManager.GetString("ConcurrentVideoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per time interval (s):.
        /// </summary>
        public static string ConnectionTimeInterval {
            get {
                return ResourceManager.GetString("ConnectionTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy url.
        /// </summary>
        public static string CopyUrl {
            get {
                return ResourceManager.GetString("CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl.
        /// </summary>
        public static string Crawl {
            get {
                return ResourceManager.GetString("Crawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl selection.
        /// </summary>
        public static string CrawlSelection {
            get {
                return ResourceManager.GetString("CrawlSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are applied to each blog upon addition:.
        /// </summary>
        public static string DefaultSettingsForBlogs {
            get {
                return ResourceManager.GetString("DefaultSettingsForBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete only the index files (no downloaded files).
        /// </summary>
        public static string DeleteIndex {
            get {
                return ResourceManager.GetString("DeleteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}, duplicates found: {2}.
        /// </summary>
        public static string DetailsProgress {
            get {
                return ResourceManager.GetString("DetailsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display confirmation dialogs?.
        /// </summary>
        public static string DisplayConfirmationDialog {
            get {
                return ResourceManager.GetString("DisplayConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download answer posts.
        /// </summary>
        public static string DownloadAnswers {
            get {
                return ResourceManager.GetString("DownloadAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download audio meta.
        /// </summary>
        public static string DownloadAudioMeta {
            get {
                return ResourceManager.GetString("DownloadAudioMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download audio files.
        /// </summary>
        public static string DownloadAudios {
            get {
                return ResourceManager.GetString("DownloadAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download catbox.
        /// </summary>
        public static string DownloadCatBox {
            get {
                return ResourceManager.GetString("DownloadCatBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download conversation posts.
        /// </summary>
        public static string DownloadConversations {
            get {
                return ResourceManager.GetString("DownloadConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded Files.
        /// </summary>
        public static string DownloadedFiles {
            get {
                return ResourceManager.GetString("DownloadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file {0} of {1}.
        /// </summary>
        public static string DownloadedFilesOf {
            get {
                return ResourceManager.GetString("DownloadedFilesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from:.
        /// </summary>
        public static string DownloadFrom {
            get {
                return ResourceManager.GetString("DownloadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download gfycat.
        /// </summary>
        public static string DownloadGfycat {
            get {
                return ResourceManager.GetString("DownloadGfycat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download image meta.
        /// </summary>
        public static string DownloadImageMeta {
            get {
                return ResourceManager.GetString("DownloadImageMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images.
        /// </summary>
        public static string DownloadImages {
            get {
                return ResourceManager.GetString("DownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download imgur.
        /// </summary>
        public static string DownloadImgur {
            get {
                return ResourceManager.GetString("DownloadImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download link posts.
        /// </summary>
        public static string DownloadLinks {
            get {
                return ResourceManager.GetString("DownloadLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download location.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download lolisafe.
        /// </summary>
        public static string DownloadLoliSafe {
            get {
                return ResourceManager.GetString("DownloadLoliSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download mixtape.
        /// </summary>
        public static string DownloadMixtape {
            get {
                return ResourceManager.GetString("DownloadMixtape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download pages: .
        /// </summary>
        public static string DownloadPages {
            get {
                return ResourceManager.GetString("DownloadPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download quote posts.
        /// </summary>
        public static string DownloadQuotes {
            get {
                return ResourceManager.GetString("DownloadQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download reblogged posts.
        /// </summary>
        public static string DownloadRebloggedPosts {
            get {
                return ResourceManager.GetString("DownloadRebloggedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download safemoe.
        /// </summary>
        public static string DownloadSafeMoe {
            get {
                return ResourceManager.GetString("DownloadSafeMoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download text posts.
        /// </summary>
        public static string DownloadTexts {
            get {
                return ResourceManager.GetString("DownloadTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string DownloadTo {
            get {
                return ResourceManager.GetString("DownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download uguu.
        /// </summary>
        public static string DownloadUguu {
            get {
                return ResourceManager.GetString("DownloadUguu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download url list.
        /// </summary>
        public static string DownloadUrlList {
            get {
                return ResourceManager.GetString("DownloadUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download video meta.
        /// </summary>
        public static string DownloadVideoMeta {
            get {
                return ResourceManager.GetString("DownloadVideoMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download videos (tumblr.com self hosted).
        /// </summary>
        public static string DownloadVideos {
            get {
                return ResourceManager.GetString("DownloadVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download videos.
        /// </summary>
        public static string DownloadVideosShort {
            get {
                return ResourceManager.GetString("DownloadVideosShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download webmshare.
        /// </summary>
        public static string DownloadWebmshare {
            get {
                return ResourceManager.GetString("DownloadWebmshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump crawler data.
        /// </summary>
        public static string DumpCrawlerData {
            get {
                return ResourceManager.GetString("DumpCrawlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download at.
        /// </summary>
        public static string EnableAutoDownload {
            get {
                return ResourceManager.GetString("EnableAutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on/off.
        /// </summary>
        public static string EnablePreview {
            get {
                return ResourceManager.GetString("EnablePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue selection.
        /// </summary>
        public static string EnqueueSelection {
            get {
                return ResourceManager.GetString("EnqueueSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}: {1}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Blogs.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string ExternalSettings {
            get {
                return ResourceManager.GetString("ExternalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download location.
        /// </summary>
        public static string FileDownloadLocation {
            get {
                return ResourceManager.GetString("FileDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force rescan.
        /// </summary>
        public static string ForceRescan {
            get {
                return ResourceManager.GetString("ForceRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download specified size even if it is not offered.
        /// </summary>
        public static string ForceSize {
            get {
                return ResourceManager.GetString("ForceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreenView.
        /// </summary>
        public static string FullScreenMedia {
            get {
                return ResourceManager.GetString("FullScreenMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings:.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size (px).
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Bit.
        /// </summary>
        public static string Info32Bit {
            get {
                return ResourceManager.GetString("Info32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 Bit.
        /// </summary>
        public static string Info64Bit {
            get {
                return ResourceManager.GetString("Info64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error description.
        /// </summary>
        public static string InternalErrorDescription {
            get {
                return ResourceManager.GetString("InternalErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 0 and 2,147,483,647..
        /// </summary>
        public static string IntRangeError {
            get {
                return ResourceManager.GetString("IntRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be of type integer..
        /// </summary>
        public static string IntTypeError {
            get {
                return ResourceManager.GetString("IntTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Complete Crawl.
        /// </summary>
        public static string LastCompleteCrawl {
            get {
                return ResourceManager.GetString("LastCompleteCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Tumblr API connections:.
        /// </summary>
        public static string LimitConnections {
            get {
                return ResourceManager.GetString("LimitConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the scan bandwidth.
        /// </summary>
        public static string LimitScan {
            get {
                return ResourceManager.GetString("LimitScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for file existence globally across all loaded blogs.
        /// </summary>
        public static string LoadAllDatabases {
            get {
                return ResourceManager.GetString("LoadAllDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of connections:.
        /// </summary>
        public static string MaxConnections {
            get {
                return ResourceManager.GetString("MaxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata format.
        /// </summary>
        public static string MetadataFormat {
            get {
                return ResourceManager.GetString("MetadataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        public static string NetFramework {
            get {
                return ResourceManager.GetString("NetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Downloads.
        /// </summary>
        public static string NumberOfDownloads {
            get {
                return ResourceManager.GetString("NumberOfDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Posts.
        /// </summary>
        public static string NumberOfImages {
            get {
                return ResourceManager.GetString("NumberOfImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Blogs.
        /// </summary>
        public static string NumberOfItems {
            get {
                return ResourceManager.GetString("NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Blog.
        /// </summary>
        public static string OneItem {
            get {
                return ResourceManager.GetString("OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open queue.
        /// </summary>
        public static string OpenQueue {
            get {
                return ResourceManager.GetString("OpenQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts per page:.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate portable mode.
        /// </summary>
        public static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of posts:.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy:.
        /// </summary>
        public static string ProxyHost {
            get {
                return ResourceManager.GetString("ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Password:.
        /// </summary>
        public static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Username:.
        /// </summary>
        public static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Blog.
        /// </summary>
        public static string RemoveBlog {
            get {
                return ResourceManager.GetString("RemoveBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Queue.
        /// </summary>
        public static string RemoveFromQueue {
            get {
                return ResourceManager.GetString("RemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blog index after crawl.
        /// </summary>
        public static string RemoveIndex {
            get {
                return ResourceManager.GetString("RemoveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save queue.
        /// </summary>
        public static string SaveQueue {
            get {
                return ResourceManager.GetString("SaveQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan connections.
        /// </summary>
        public static string ScanConnections {
            get {
                return ResourceManager.GetString("ScanConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a blog.
        /// </summary>
        public static string SelectABlog {
            get {
                return ResourceManager.GetString("SelectABlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Return.
        /// </summary>
        public static string ShiftReturn {
            get {
                return ResourceManager.GetString("ShiftReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files.
        /// </summary>
        public static string ShowFiles {
            get {
                return ResourceManager.GetString("ShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of {0} blogs.
        /// </summary>
        public static string ShowItems {
            get {
                return ResourceManager.GetString("ShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip .gif files.
        /// </summary>
        public static string SkipGif {
            get {
                return ResourceManager.GetString("SkipGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFA detected, enter auth code:.
        /// </summary>
        public static string TFANeeded {
            get {
                return ResourceManager.GetString("TFANeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Software.
        /// </summary>
        public static string ThirdPartySoftware {
            get {
                return ResourceManager.GetString("ThirdPartySoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Software and Licenses.
        /// </summary>
        public static string ThirdPartySoftwareDescription {
            get {
                return ResourceManager.GetString("ThirdPartySoftwareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (s).
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hh:mm:ss) and add.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must have to form hh:mm:ss..
        /// </summary>
        public static string TimeSpanTypeError {
            get {
                return ResourceManager.GetString("TimeSpanTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to the tumblr.com network.
        /// </summary>
        public static string ToolTipAuthenticate {
            get {
                return ResourceManager.GetString("ToolTipAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to the tumblr.com network.
        /// </summary>
        public static string ToolTipAuthenticateBrowser {
            get {
                return ResourceManager.GetString("ToolTipAuthenticateBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a browser window to authenticate yourself to the tumblr.com site.
        ///The cookie with your credentials of your account is saved and the authentication process needs to be done only once..
        /// </summary>
        public static string ToolTipAuthenticateBrowserDescription {
            get {
                return ResourceManager.GetString("ToolTipAuthenticateBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to the tumblr.com network.
        /// </summary>
        public static string ToolTipAuthenticateDescription {
            get {
                return ResourceManager.GetString("ToolTipAuthenticateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of concurrent processing blogs.
        /// </summary>
        public static string ToolTipBlogs {
            get {
                return ResourceManager.GetString("ToolTipBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the number of concurrent processing blogs.
        ///Setting this to 2 would process two blogs at a time..
        /// </summary>
        public static string ToolTipBlogsDescription {
            get {
                return ResourceManager.GetString("ToolTipBlogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipCatBoxFiletype {
            get {
                return ResourceManager.GetString("ToolTipCatBoxFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipCatBoxFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipCatBoxFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks the directory for already downloaded files..
        /// </summary>
        public static string ToolTipCheckDirectoryForFiles {
            get {
                return ResourceManager.GetString("ToolTipCheckDirectoryForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks the directory and the database for already downloaded files.
        ///Might negatively impact the download speed for large directories..
        /// </summary>
        public static string ToolTipCheckDirectoryForFilesDescription {
            get {
                return ResourceManager.GetString("ToolTipCheckDirectoryForFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of total concurrent connections.
        /// </summary>
        public static string ToolTipConnections {
            get {
                return ResourceManager.GetString("ToolTipConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the number of total concurrent connections.
        ///The number is shared between all actively downloading blogs..
        /// </summary>
        public static string ToolTipConnectionsDescription {
            get {
                return ResourceManager.GetString("ToolTipConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the default settings for newly added blogs..
        /// </summary>
        public static string ToolTipDefaultSettingsForBlogs {
            get {
                return ResourceManager.GetString("ToolTipDefaultSettingsForBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan/download uses indivual settings for each blog.
        ///To change them, select blog(s) in the main interface and select the Details tab on the right hand side..
        /// </summary>
        public static string ToolTipDefaultSettingsForBlogsDescription {
            get {
                return ResourceManager.GetString("ToolTipDefaultSettingsForBlogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of downloaded post types of total post types.
        /// </summary>
        public static string ToolTipDetailsStats {
            get {
                return ResourceManager.GetString("ToolTipDetailsStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to download post type or skip during the download.
        /// </summary>
        public static string ToolTipDetailsStatsDescription {
            get {
                return ResourceManager.GetString("ToolTipDetailsStatsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked CatBox files.
        /// </summary>
        public static string ToolTipDownloadCatBox {
            get {
                return ResourceManager.GetString("ToolTipDownloadCatBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted CatBox files.
        /// </summary>
        public static string ToolTipDownloadCatBoxDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadCatBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl posts from this date.
        /// </summary>
        public static string ToolTipDownloadFrom {
            get {
                return ResourceManager.GetString("ToolTipDownloadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in YYYYMMDD format. Empty means from the beginning of the blog..
        /// </summary>
        public static string ToolTipDownloadFromDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadFromDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked gfycat.com files.
        /// </summary>
        public static string ToolTipDownloadGfycat {
            get {
                return ResourceManager.GetString("ToolTipDownloadGfycat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted gfycat.com files.
        /// </summary>
        public static string ToolTipDownloadGfycatDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadGfycatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked imgur.com files.
        /// </summary>
        public static string ToolTipDownloadImgur {
            get {
                return ResourceManager.GetString("ToolTipDownloadImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted imgur.com files.
        /// </summary>
        public static string ToolTipDownloadImgurDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadImgurDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked LoliSafe files.
        /// </summary>
        public static string ToolTipDownloadLoliSafe {
            get {
                return ResourceManager.GetString("ToolTipDownloadLoliSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted LoliSafe files.
        /// </summary>
        public static string ToolTipDownloadLoliSafeDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadLoliSafeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked Mixtape.moe files.
        /// </summary>
        public static string ToolTipDownloadMixtape {
            get {
                return ResourceManager.GetString("ToolTipDownloadMixtape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted Mixtape.moe files.
        /// </summary>
        public static string ToolTipDownloadMixtapeDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadMixtapeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download only specific pages.
        /// </summary>
        public static string ToolTipDownloadPages {
            get {
                return ResourceManager.GetString("ToolTipDownloadPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible notations are: 1 or 1-3 or 1,2,3. Empty means the whole blog..
        /// </summary>
        public static string ToolTipDownloadPagesDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadPagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked SafeMoe files.
        /// </summary>
        public static string ToolTipDownloadSafeMoe {
            get {
                return ResourceManager.GetString("ToolTipDownloadSafeMoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted SafeMoe files.
        /// </summary>
        public static string ToolTipDownloadSafeMoeDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadSafeMoeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in YYYYMMDD format. Empty means from May 2007..
        /// </summary>
        public static string ToolTipDownloadTagsFromDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadTagsFromDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in YYYYMMDD format. Empty means to now..
        /// </summary>
        public static string ToolTipDownloadTagsToDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadTagsToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl posts to this date.
        /// </summary>
        public static string ToolTipDownloadTo {
            get {
                return ResourceManager.GetString("ToolTipDownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in YYYYMMDD format. Empty means to now..
        /// </summary>
        public static string ToolTipDownloadToDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked Uguu files.
        /// </summary>
        public static string ToolTipDownloadUguu {
            get {
                return ResourceManager.GetString("ToolTipDownloadUguu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted Uguu files.
        /// </summary>
        public static string ToolTipDownloadUguuDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadUguuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a url list..
        /// </summary>
        public static string ToolTipDownloadUrlList {
            get {
                return ResourceManager.GetString("ToolTipDownloadUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads a url list of the binary files instead of the actual files.
        /// </summary>
        public static string ToolTipDownloadUrlListDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadUrlListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download linked webmshare.com files.
        /// </summary>
        public static string ToolTipDownloadWebmshare {
            get {
                return ResourceManager.GetString("ToolTipDownloadWebmshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download externally hosted webmshare.com files.
        /// </summary>
        public static string ToolTipDownloadWebmshareDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadWebmshareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump the crawler data to disk..
        /// </summary>
        public static string ToolTipDumpCrawlerData {
            get {
                return ResourceManager.GetString("ToolTipDumpCrawlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes the data gather from the crawler to disk, separated per post..
        /// </summary>
        public static string ToolTipDumpCrawlerDataDescription {
            get {
                return ResourceManager.GetString("ToolTipDumpCrawlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all blog urls as text file.
        /// </summary>
        public static string ToolTipExportBlogs {
            get {
                return ResourceManager.GetString("ToolTipExportBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all urls as a text file for exchange..
        /// </summary>
        public static string ToolTipExportBlogsDescription {
            get {
                return ResourceManager.GetString("ToolTipExportBlogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides the default download location.
        /// </summary>
        public static string ToolTipFileDownloadLocation {
            get {
                return ResourceManager.GetString("ToolTipFileDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not empty, all files are downloaded in the specified folder.
        /// </summary>
        public static string ToolTipFileDownloadLocationDescription {
            get {
                return ResourceManager.GetString("ToolTipFileDownloadLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescans the whole blog, not just new posts..
        /// </summary>
        public static string ToolTipForceRescan {
            get {
                return ResourceManager.GetString("ToolTipForceRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces a complete scan using the Tumblr api..
        /// </summary>
        public static string ToolTipForceRescanDescription {
            get {
                return ResourceManager.GetString("ToolTipForceRescanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the specified resolution of images even if the size is not offered..
        /// </summary>
        public static string ToolTipForceSize {
            get {
                return ResourceManager.GetString("ToolTipForceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the crawler only finds lower sized images than specified, enabling this option will rename the url to the specified files size.
        ///Those files generally exist and sometimes offer a larger resolution or are just renamed smaller resolution files.
        ///It&apos;s safe to turn this on..
        /// </summary>
        public static string ToolTipForceSizeDescription {
            get {
                return ResourceManager.GetString("ToolTipForceSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipGfycatFiletype {
            get {
                return ResourceManager.GetString("ToolTipGfycatFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipGfycatFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipGfycatFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttles the bandwidth of the downloader.
        /// </summary>
        public static string ToolTipLimitBandwidth {
            get {
                return ResourceManager.GetString("ToolTipLimitBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maximum bandwidth available for the downloader in kbytes/s.
        ///0 disables throttling..
        /// </summary>
        public static string ToolTipLimitBandwidthDescription {
            get {
                return ResourceManager.GetString("ToolTipLimitBandwidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit connections to the tumblr api..
        /// </summary>
        public static string ToolTipLimitConnections {
            get {
                return ResourceManager.GetString("ToolTipLimitConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A too high value will forcefully close connections (429 -- Limit Exceeded) made to the tumblr api.
        ///A too small value will decrease the scanning speed.
        ///Set a number/time pair.
        ///Note: The tumblr api is only used for regular tumblr blog downloads..
        /// </summary>
        public static string ToolTipLimitConnectionsDescription {
            get {
                return ResourceManager.GetString("ToolTipLimitConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the scan bandwidth in the throttling.
        /// </summary>
        public static string ToolTipLimitScan {
            get {
                return ResourceManager.GetString("ToolTipLimitScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the data used for scanning is usually small, you should leave this off
        ///since the throttling algorithm is too slow to adjust and might negatively impact the scan performance..
        /// </summary>
        public static string ToolTipLimitScanDescription {
            get {
                return ResourceManager.GetString("ToolTipLimitScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During an active crawl each file is checked globally if it already exists instead of blog wise..
        /// </summary>
        public static string ToolTipLoadAllDatabases {
            get {
                return ResourceManager.GetString("ToolTipLoadAllDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When crawling a blog, all posts are compared against each other before downloading to prevent the download of duplicate binary files.
        ///This is done blog wise. Enabling this options will compare each file globally.
        ///Activation will increase the memory usage during operation based on the amount of already downloaded content..
        /// </summary>
        public static string ToolTipLoadAllDatabasesDescription {
            get {
                return ResourceManager.GetString("ToolTipLoadAllDatabasesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from Tumblr.com.
        /// </summary>
        public static string ToolTipLogout {
            get {
                return ResourceManager.GetString("ToolTipLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the cookies used for authentication from the system..
        /// </summary>
        public static string ToolTipLogoutDescription {
            get {
                return ResourceManager.GetString("ToolTipLogoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipLoliSafeFiletype {
            get {
                return ResourceManager.GetString("ToolTipLoliSafeFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipLoliSafeFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipLoliSafeFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipMixtapeFiletype {
            get {
                return ResourceManager.GetString("ToolTipMixtapeFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipMixtapeFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipMixtapeFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts per Page.
        /// </summary>
        public static string ToolTipPageSize {
            get {
                return ResourceManager.GetString("ToolTipPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the post per page (should be between 1-50, default 50).
        ///E.g. 50 means to scan 50 posts per page..
        /// </summary>
        public static string ToolTipPageSizeDescription {
            get {
                return ResourceManager.GetString("ToolTipPageSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts per Page.
        /// </summary>
        public static string ToolTipPageSizeTumblrSearch {
            get {
                return ResourceManager.GetString("ToolTipPageSizeTumblrSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the post per page. E.g. 50 means to scan 50 posts per page..
        /// </summary>
        public static string ToolTipPageSizeTumblrSearchDescription {
            get {
                return ResourceManager.GetString("ToolTipPageSizeTumblrSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for password-protected blogs.
        /// </summary>
        public static string ToolTipPassword {
            get {
                return ResourceManager.GetString("ToolTipPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution: The password is stored in clear text in the blogs database..
        /// </summary>
        public static string ToolTipPasswordDescription {
            get {
                return ResourceManager.GetString("ToolTipPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates the portable mode..
        /// </summary>
        public static string ToolTipPortableMode {
            get {
                return ResourceManager.GetString("ToolTipPortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the settings in the folder of the executable instead of AppData..
        /// </summary>
        public static string ToolTipPortableModeDescription {
            get {
                return ResourceManager.GetString("ToolTipPortableModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for non-anonymous proxy server.
        /// </summary>
        public static string ToolTipProxyPassword {
            get {
                return ResourceManager.GetString("ToolTipProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are saved in clear text in the settings file.
        /// </summary>
        public static string ToolTipProxyPasswordDescription {
            get {
                return ResourceManager.GetString("ToolTipProxyPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipSafeMoeFiletype {
            get {
                return ResourceManager.GetString("ToolTipSafeMoeFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipSafeMoeFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipSafeMoeFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of connections used for each scan.
        /// </summary>
        public static string ToolTipScan {
            get {
                return ResourceManager.GetString("ToolTipScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the number connections used for scanning.
        ///Since the data is usually small, you should leave this high.
        ///Note: This setting has no impact if the Limit Tumblr Api Connections setting is turned on..
        /// </summary>
        public static string ToolTipScanDescription {
            get {
                return ResourceManager.GetString("ToolTipScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download only tagged posts.
        /// </summary>
        public static string ToolTipTags {
            get {
                return ResourceManager.GetString("ToolTipTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in a comma separated list without the leading hash (#) sign.
        ///E.g.  great big car, bears searches for great big cars and bears..
        /// </summary>
        public static string ToolTipTagsDescription {
            get {
                return ResourceManager.GetString("ToolTipTagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout for web requests.
        /// </summary>
        public static string ToolTipTimeout {
            get {
                return ResourceManager.GetString("ToolTipTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time, in seconds, until the request times out..
        /// </summary>
        public static string ToolTipTimeoutDescription {
            get {
                return ResourceManager.GetString("ToolTipTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tumblr login.
        /// </summary>
        public static string ToolTipTumblrLogin {
            get {
                return ResourceManager.GetString("ToolTipTumblrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login is not saved locally but only used for generating a cookie..
        /// </summary>
        public static string ToolTipTumblrLoginDescription {
            get {
                return ResourceManager.GetString("ToolTipTumblrLoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tumblr password.
        /// </summary>
        public static string ToolTipTumblrPassword {
            get {
                return ResourceManager.GetString("ToolTipTumblrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is not saved locally but only used for generating a cookie..
        /// </summary>
        public static string ToolTipTumblrPasswordDescription {
            get {
                return ResourceManager.GetString("ToolTipTumblrPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipUguuFiletype {
            get {
                return ResourceManager.GetString("ToolTipUguuFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipUguuFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipUguuFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of concurrent connections to the tumblr video host.
        /// </summary>
        public static string ToolTipVideoConnections {
            get {
                return ResourceManager.GetString("ToolTipVideoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vt.tumblr.com host regularly closes connections if the number is too high..
        /// </summary>
        public static string ToolTipVideoConnectionsDescription {
            get {
                return ResourceManager.GetString("ToolTipVideoConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type to download.
        /// </summary>
        public static string ToolTipWebmshareFiletype {
            get {
                return ResourceManager.GetString("ToolTipWebmshareFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose which file type you want to download.
        /// </summary>
        public static string ToolTipWebmshareFiletypeDescription {
            get {
                return ResourceManager.GetString("ToolTipWebmshareFiletypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr login.
        /// </summary>
        public static string TumblrLogin {
            get {
                return ResourceManager.GetString("TumblrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr password.
        /// </summary>
        public static string TumblrPassword {
            get {
                return ResourceManager.GetString("TumblrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Application Error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User agent.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size (px).
        /// </summary>
        public static string VideoSize {
            get {
                return ResourceManager.GetString("VideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the site in the web browser.
        /// </summary>
        public static string VisitBlog {
            get {
                return ResourceManager.GetString("VisitBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
