//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblThree.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TumblThree.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blog.
        /// </summary>
        public static string AddBlog {
            get {
                return ResourceManager.GetString("AddBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Bandwidth (KB/s).
        /// </summary>
        public static string Bandwidth {
            get {
                return ResourceManager.GetString("Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 0 and 9,000,000,000,000,000..
        /// </summary>
        public static string BandwidthRangeError {
            get {
                return ResourceManager.GetString("BandwidthRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog settings:.
        /// </summary>
        public static string BlogSettings {
            get {
                return ResourceManager.GetString("BlogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog stats:.
        /// </summary>
        public static string BlogStatistics {
            get {
                return ResourceManager.GetString("BlogStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL:.
        /// </summary>
        public static string BlogUrl {
            get {
                return ResourceManager.GetString("BlogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check directory for files.
        /// </summary>
        public static string CheckDirectoryForFiles {
            get {
                return ResourceManager.GetString("CheckDirectoryForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check blog online status on startup.
        /// </summary>
        public static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        public static string ClearQueue {
            get {
                return ResourceManager.GetString("ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Clipboard.
        /// </summary>
        public static string ClipboardMonitor {
            get {
                return ResourceManager.GetString("ClipboardMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval (s):.
        /// </summary>
        public static string ConnectionTimeInterval {
            get {
                return ResourceManager.GetString("ConnectionTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy url.
        /// </summary>
        public static string CopyUrl {
            get {
                return ResourceManager.GetString("CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl.
        /// </summary>
        public static string Crawl {
            get {
                return ResourceManager.GetString("Crawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl selection.
        /// </summary>
        public static string CrawlSelection {
            get {
                return ResourceManager.GetString("CrawlSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings applied to each blog upon addition:.
        /// </summary>
        public static string DefaultSettingsForBlogs {
            get {
                return ResourceManager.GetString("DefaultSettingsForBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete only the index files (no downloaded files).
        /// </summary>
        public static string DeleteIndex {
            get {
                return ResourceManager.GetString("DeleteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}, duplicates found: {2}.
        /// </summary>
        public static string DetailsProgress {
            get {
                return ResourceManager.GetString("DetailsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download answer posts.
        /// </summary>
        public static string DownloadAnswers {
            get {
                return ResourceManager.GetString("DownloadAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download audio meta.
        /// </summary>
        public static string DownloadAudioMeta {
            get {
                return ResourceManager.GetString("DownloadAudioMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download audio files.
        /// </summary>
        public static string DownloadAudios {
            get {
                return ResourceManager.GetString("DownloadAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download conversation posts.
        /// </summary>
        public static string DownloadConversations {
            get {
                return ResourceManager.GetString("DownloadConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded Files.
        /// </summary>
        public static string DownloadedFiles {
            get {
                return ResourceManager.GetString("DownloadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file {0} of {1}.
        /// </summary>
        public static string DownloadedFilesOf {
            get {
                return ResourceManager.GetString("DownloadedFilesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download From:.
        /// </summary>
        public static string DownloadFrom {
            get {
                return ResourceManager.GetString("DownloadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download image meta.
        /// </summary>
        public static string DownloadImageMeta {
            get {
                return ResourceManager.GetString("DownloadImageMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images.
        /// </summary>
        public static string DownloadImages {
            get {
                return ResourceManager.GetString("DownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download link posts.
        /// </summary>
        public static string DownloadLinks {
            get {
                return ResourceManager.GetString("DownloadLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download location.
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download pages: .
        /// </summary>
        public static string DownloadPages {
            get {
                return ResourceManager.GetString("DownloadPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download quote posts.
        /// </summary>
        public static string DownloadQuotes {
            get {
                return ResourceManager.GetString("DownloadQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download reblogged posts.
        /// </summary>
        public static string DownloadRebloggedPosts {
            get {
                return ResourceManager.GetString("DownloadRebloggedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download text posts.
        /// </summary>
        public static string DownloadTexts {
            get {
                return ResourceManager.GetString("DownloadTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string DownloadTo {
            get {
                return ResourceManager.GetString("DownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download url list.
        /// </summary>
        public static string DownloadUrlList {
            get {
                return ResourceManager.GetString("DownloadUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download video meta.
        /// </summary>
        public static string DownloadVideoMeta {
            get {
                return ResourceManager.GetString("DownloadVideoMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download videos (tumblr.com self hosted).
        /// </summary>
        public static string DownloadVideos {
            get {
                return ResourceManager.GetString("DownloadVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download videos.
        /// </summary>
        public static string DownloadVideosShort {
            get {
                return ResourceManager.GetString("DownloadVideosShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable autodownload blogs and add.
        /// </summary>
        public static string EnableAutoDownload {
            get {
                return ResourceManager.GetString("EnableAutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on/off.
        /// </summary>
        public static string EnablePreview {
            get {
                return ResourceManager.GetString("EnablePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue selection.
        /// </summary>
        public static string EnqueueSelection {
            get {
                return ResourceManager.GetString("EnqueueSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}: {1}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Blogs.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force rescan.
        /// </summary>
        public static string ForceRescan {
            get {
                return ResourceManager.GetString("ForceRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download specified size even if it is not offered.
        /// </summary>
        public static string ForceSize {
            get {
                return ResourceManager.GetString("ForceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreenView.
        /// </summary>
        public static string FullScreenMedia {
            get {
                return ResourceManager.GetString("FullScreenMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings:.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size (px).
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Bit.
        /// </summary>
        public static string Info32Bit {
            get {
                return ResourceManager.GetString("Info32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 Bit.
        /// </summary>
        public static string Info64Bit {
            get {
                return ResourceManager.GetString("Info64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error description.
        /// </summary>
        public static string InternalErrorDescription {
            get {
                return ResourceManager.GetString("InternalErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 0 and 2,147,483,647..
        /// </summary>
        public static string IntRangeError {
            get {
                return ResourceManager.GetString("IntRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be of type integer..
        /// </summary>
        public static string IntTypeError {
            get {
                return ResourceManager.GetString("IntTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Complete Crawl.
        /// </summary>
        public static string LastCompleteCrawl {
            get {
                return ResourceManager.GetString("LastCompleteCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Tumblr Api Connections.
        /// </summary>
        public static string LimitConnections {
            get {
                return ResourceManager.GetString("LimitConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the scan bandwidth.
        /// </summary>
        public static string LimitScan {
            get {
                return ResourceManager.GetString("LimitScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of connections:.
        /// </summary>
        public static string MaxConnections {
            get {
                return ResourceManager.GetString("MaxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        public static string NetFramework {
            get {
                return ResourceManager.GetString("NetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Downloads.
        /// </summary>
        public static string NumberOfDownloads {
            get {
                return ResourceManager.GetString("NumberOfDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Images.
        /// </summary>
        public static string NumberOfImages {
            get {
                return ResourceManager.GetString("NumberOfImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Items.
        /// </summary>
        public static string NumberOfItems {
            get {
                return ResourceManager.GetString("NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Item.
        /// </summary>
        public static string OneItem {
            get {
                return ResourceManager.GetString("OneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open queue.
        /// </summary>
        public static string OpenQueue {
            get {
                return ResourceManager.GetString("OpenQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts per page:.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel blogs.
        /// </summary>
        public static string ParallelBlogs {
            get {
                return ResourceManager.GetString("ParallelBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel connections.
        /// </summary>
        public static string ParallelConnections {
            get {
                return ResourceManager.GetString("ParallelConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate portable mode..
        /// </summary>
        public static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of posts:.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy:.
        /// </summary>
        public static string ProxyHost {
            get {
                return ResourceManager.GetString("ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Password:.
        /// </summary>
        public static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Username:.
        /// </summary>
        public static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Blog.
        /// </summary>
        public static string RemoveBlog {
            get {
                return ResourceManager.GetString("RemoveBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Queue.
        /// </summary>
        public static string RemoveFromQueue {
            get {
                return ResourceManager.GetString("RemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blog index after crawl.
        /// </summary>
        public static string RemoveIndex {
            get {
                return ResourceManager.GetString("RemoveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save queue.
        /// </summary>
        public static string SaveQueue {
            get {
                return ResourceManager.GetString("SaveQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan connections.
        /// </summary>
        public static string ScanConnections {
            get {
                return ResourceManager.GetString("ScanConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a blog.
        /// </summary>
        public static string SelectABlog {
            get {
                return ResourceManager.GetString("SelectABlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Return.
        /// </summary>
        public static string ShiftReturn {
            get {
                return ResourceManager.GetString("ShiftReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Files.
        /// </summary>
        public static string ShowFiles {
            get {
                return ResourceManager.GetString("ShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of {0} blogs.
        /// </summary>
        public static string ShowItems {
            get {
                return ResourceManager.GetString("ShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip .gif files.
        /// </summary>
        public static string SkipGif {
            get {
                return ResourceManager.GetString("SkipGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Software.
        /// </summary>
        public static string ThirdPartySoftware {
            get {
                return ResourceManager.GetString("ThirdPartySoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Software and Licenses.
        /// </summary>
        public static string ThirdPartySoftwareDescription {
            get {
                return ResourceManager.GetString("ThirdPartySoftwareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (s).
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at time (hh:mm:ss).
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must have to form hh:mm:ss..
        /// </summary>
        public static string TimeSpanTypeError {
            get {
                return ResourceManager.GetString("TimeSpanTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to the tumblr.com network.
        /// </summary>
        public static string ToolTipAuthenticate {
            get {
                return ResourceManager.GetString("ToolTipAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a browser window to authenticate yourself to the tumblr.com site. Allows the download of private blogs with your account. The access token to your account is saved and the authentication process needs to be done only once..
        /// </summary>
        public static string ToolTipAuthenticateDescription {
            get {
                return ResourceManager.GetString("ToolTipAuthenticateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of simultaneous processed blogs.
        /// </summary>
        public static string ToolTipBlogs {
            get {
                return ResourceManager.GetString("ToolTipBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the Number of simultaneous processed blogs. Setting this to 2 would download data from two blogs at a time..
        /// </summary>
        public static string ToolTipBlogsDescription {
            get {
                return ResourceManager.GetString("ToolTipBlogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks the directory for already downloaded files..
        /// </summary>
        public static string ToolTipCheckDirectoryForFiles {
            get {
                return ResourceManager.GetString("ToolTipCheckDirectoryForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks the directory and the database for already downloaded files. Might negatively impact the download speed for large directories..
        /// </summary>
        public static string ToolTipCheckDirectoryForFilesDescription {
            get {
                return ResourceManager.GetString("ToolTipCheckDirectoryForFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of total simultaneous connections.
        /// </summary>
        public static string ToolTipConnections {
            get {
                return ResourceManager.GetString("ToolTipConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the Number of total simultaneous connections. The number is divided by the number of Parallel Blogs settings. 25/2 would open 12 connections per blog download..
        /// </summary>
        public static string ToolTipConnectionsDescription {
            get {
                return ResourceManager.GetString("ToolTipConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the default settings for newly added blogs..
        /// </summary>
        public static string ToolTipDefaultSettingsForBlogs {
            get {
                return ResourceManager.GetString("ToolTipDefaultSettingsForBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup uses indivual settings for each blog. To change them, select a blog in the main interface and select the Details window on the right hand side..
        /// </summary>
        public static string ToolTipDefaultSettingsForBlogsDescription {
            get {
                return ResourceManager.GetString("ToolTipDefaultSettingsForBlogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of downloaded post types / total post types.
        /// </summary>
        public static string ToolTipDetailsStats {
            get {
                return ResourceManager.GetString("ToolTipDetailsStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to download post type or skip during the backup.
        /// </summary>
        public static string ToolTipDetailsStatsDescription {
            get {
                return ResourceManager.GetString("ToolTipDetailsStatsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl posts from this date.
        /// </summary>
        public static string ToolTipDownloadFrom {
            get {
                return ResourceManager.GetString("ToolTipDownloadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in YYYYMMDD format. Empty means from May 2007..
        /// </summary>
        public static string ToolTipDownloadFromDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadFromDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download only specific pages.
        /// </summary>
        public static string ToolTipDownloadPages {
            get {
                return ResourceManager.GetString("ToolTipDownloadPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible notations are: 1 or 1-3 or 1,2,3. Empty means the whole blog..
        /// </summary>
        public static string ToolTipDownloadPagesDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadPagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl posts to this date.
        /// </summary>
        public static string ToolTipDownloadTo {
            get {
                return ResourceManager.GetString("ToolTipDownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in YYYYMMDD format. Empty means to now..
        /// </summary>
        public static string ToolTipDownloadToDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a url list..
        /// </summary>
        public static string ToolTipDownloadUrlList {
            get {
                return ResourceManager.GetString("ToolTipDownloadUrlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads a url list of the binary files instead of the actual files.
        /// </summary>
        public static string ToolTipDownloadUrlListDescription {
            get {
                return ResourceManager.GetString("ToolTipDownloadUrlListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all blog urls as text file.
        /// </summary>
        public static string ToolTipExportBlogs {
            get {
                return ResourceManager.GetString("ToolTipExportBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all urls as a text file for exchange..
        /// </summary>
        public static string ToolTipExportBlogsDescription {
            get {
                return ResourceManager.GetString("ToolTipExportBlogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescans the whole blog, not just new posts..
        /// </summary>
        public static string ToolTipForceRescan {
            get {
                return ResourceManager.GetString("ToolTipForceRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces a complete scan using the Tumblr api. Enabling this also updates the blog statistics..
        /// </summary>
        public static string ToolTipForceRescanDescription {
            get {
                return ResourceManager.GetString("ToolTipForceRescanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the specified resolution of images even if the size is not offered..
        /// </summary>
        public static string ToolTipForceSize {
            get {
                return ResourceManager.GetString("ToolTipForceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the crawler only finds lower sized images than specified, enabling this option will rename the url to the specified files size. Those files generally exist and sometimes offer a larger resolution or are just renamed smaller resolution files. It&apos;s safe to turn this on..
        /// </summary>
        public static string ToolTipForceSizeDescription {
            get {
                return ResourceManager.GetString("ToolTipForceSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttles the bandwidth of the downloader.
        /// </summary>
        public static string ToolTipLimitBandwidth {
            get {
                return ResourceManager.GetString("ToolTipLimitBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maximum bandwidth available for the downloader in kbytes/s. 0 disables throttling..
        /// </summary>
        public static string ToolTipLimitBandwidthDescription {
            get {
                return ResourceManager.GetString("ToolTipLimitBandwidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit connections to the tumblr api..
        /// </summary>
        public static string ToolTipLimitConnections {
            get {
                return ResourceManager.GetString("ToolTipLimitConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A too high value will forcefully close connections (429 -- Limit Exceeded) made to the tumblr api. A too small value will decrease the download speed..
        /// </summary>
        public static string ToolTipLimitConnectionsDescription {
            get {
                return ResourceManager.GetString("ToolTipLimitConnectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the scan bandwidth in the throttling.
        /// </summary>
        public static string ToolTipLimitScan {
            get {
                return ResourceManager.GetString("ToolTipLimitScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the data used for scanning is usually small, you should leave this off since the throttling algorithm is too slow to adjust and will negatively impact the performance..
        /// </summary>
        public static string ToolTipLimitScanDescription {
            get {
                return ResourceManager.GetString("ToolTipLimitScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts per Page.
        /// </summary>
        public static string ToolTipPageSize {
            get {
                return ResourceManager.GetString("ToolTipPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the post per page (should be between 1-50, default 50). E.g. 50 means to scan 50 posts per page..
        /// </summary>
        public static string ToolTipPageSizeDescription {
            get {
                return ResourceManager.GetString("ToolTipPageSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates the portable mode..
        /// </summary>
        public static string ToolTipPortableMode {
            get {
                return ResourceManager.GetString("ToolTipPortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the settings in the folder of the executable instead of AppData..
        /// </summary>
        public static string ToolTipPortableModeDescription {
            get {
                return ResourceManager.GetString("ToolTipPortableModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for non-anonymous proxy server.
        /// </summary>
        public static string ToolTipProxyPassword {
            get {
                return ResourceManager.GetString("ToolTipProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are saved in clear text in the settings file.
        /// </summary>
        public static string ToolTipProxyPasswordDescription {
            get {
                return ResourceManager.GetString("ToolTipProxyPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of connections used for each scan.
        /// </summary>
        public static string ToolTipScan {
            get {
                return ResourceManager.GetString("ToolTipScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the number connections used for scanning. Since the data is usually small, you should leave this high..
        /// </summary>
        public static string ToolTipScanDescription {
            get {
                return ResourceManager.GetString("ToolTipScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Application Error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size (px).
        /// </summary>
        public static string VideoSize {
            get {
                return ResourceManager.GetString("VideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the site in the web browser.
        /// </summary>
        public static string VisitBlog {
            get {
                return ResourceManager.GetString("VisitBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
